Repository Plutonomicon/plutarch-plutus, pull requests merged in 2022-03, with the labels that each got.

#353 Avoid redundant evaluation in `@==`
  plutarch-test/src/Plutarch/IntegerSpec.hs
  plutarch-test/src/Plutarch/Test.hs
  plutarch-test/src/Plutarch/Test/Golden.hs
Labels: testing

#351 Add plutarch-extra scaffold
  CHANGELOG.md
  flake.nix
  plutarch-extra/Plutarch/Extra.hs
  plutarch-extra/plutarch-extra.cabal
  plutarch-test/Main.hs
  plutarch-test/common/Plutarch/Test.hs
  plutarch-test/common/Plutarch/Test/Benchmark.hs
  plutarch-test/common/Plutarch/Test/Golden.hs
  plutarch-test/common/Plutarch/Test/ListSyntax.hs
  plutarch-test/goldens/monadic.api.example.signatory.dev=true.bench.golden
  plutarch-test/goldens/monadic.api.example.signatory.dev=true.uplc.golden
  plutarch-test/plutarch-base/BaseSpec.hs
  plutarch-test/plutarch-base/Plutarch/ApiSpec.hs
  plutarch-test/plutarch-base/Plutarch/BoolSpec.hs
  plutarch-test/plutarch-base/Plutarch/ByteStringSpec.hs
  plutarch-test/plutarch-base/Plutarch/EitherSpec.hs
  plutarch-test/plutarch-base/Plutarch/FieldSpec.hs
  plutarch-test/plutarch-base/Plutarch/IntegerSpec.hs
  plutarch-test/plutarch-base/Plutarch/LiftSpec.hs
  plutarch-test/plutarch-base/Plutarch/ListSpec.hs
  plutarch-test/plutarch-base/Plutarch/MaybeSpec.hs
  plutarch-test/plutarch-base/Plutarch/MonadicSpec.hs
  plutarch-test/plutarch-base/Plutarch/PIsDataSpec.hs
  plutarch-test/plutarch-base/Plutarch/PLamSpec.hs
  plutarch-test/plutarch-base/Plutarch/PairSpec.hs
  plutarch-test/plutarch-base/Plutarch/PlutusTypeSpec.hs
  plutarch-test/plutarch-base/Plutarch/RationalSpec.hs
  plutarch-test/plutarch-base/Plutarch/RecSpec.hs
  plutarch-test/plutarch-base/Plutarch/RecursionSpec.hs
  plutarch-test/plutarch-base/Plutarch/ScriptsSpec.hs
  plutarch-test/plutarch-base/Plutarch/StringSpec.hs
  plutarch-test/plutarch-base/Plutarch/TraceSpec.hs
  plutarch-test/plutarch-base/Plutarch/UPLCSpec.hs
  plutarch-test/plutarch-base/Plutarch/UnitSpec.hs
  plutarch-test/plutarch-extra/ExtraSpec.hs
  plutarch-test/plutarch-extra/Plutarch/HelloSpec.hs
  plutarch-test/plutarch-test.cabal
  plutarch-test/src/Main.hs
Labels: plutarch-extra

#347 Add `psatisfyWithinBenchmark`
  plutarch-test/common/Plutarch/Test.hs
  plutarch-test/common/Plutarch/Test/Benchmark.hs
  plutarch-test/common/Plutarch/Test/Golden.hs
  plutarch-test/plutarch-base/Plutarch/IntegerSpec.hs
Labels: testing

#356 `plutarch-extra`: Export a Prelude for users of Plutarch
  CHANGELOG.md
  docs/GUIDE.md
  plutarch-extra/plutarch-extra.cabal
  plutarch-extra/preludes/PPrelude.hs
Labels: plutarch-extra

#357 Upstream @Geometer1729's list utilities
  CHANGELOG.md
  Plutarch/List.hs
  Plutarch/Prelude.hs
  Plutarch/Rational.hs
  flake.lock
  flake.nix
  plutarch-extra/Plutarch/ListUtils.hs
  plutarch-extra/plutarch-extra.cabal
  plutarch-test/common/Plutarch/Test/Property/Gen.hs
  plutarch-test/common/Plutarch/Test/Property/Util.hs
  plutarch-test/goldens/extra.listutils.bench.golden
  plutarch-test/goldens/extra.listutils.uplc.eval.golden
  plutarch-test/goldens/extra.listutils.uplc.golden
  plutarch-test/goldens/list.bench.bench.golden
  plutarch-test/goldens/list.bench.uplc.eval.golden
  plutarch-test/goldens/list.bench.uplc.golden
  plutarch-test/goldens/list.dev=false.bench.golden
  plutarch-test/goldens/list.dev=false.uplc.eval.golden
  plutarch-test/goldens/list.dev=false.uplc.golden
  plutarch-test/goldens/list.dev=true.bench.golden
  plutarch-test/goldens/list.dev=true.uplc.eval.golden
  plutarch-test/goldens/list.dev=true.uplc.golden
  plutarch-test/goldens/list.fun.bench.golden
  plutarch-test/goldens/list.fun.uplc.eval.golden
  plutarch-test/goldens/list.fun.uplc.golden
  plutarch-test/goldens/list.type.bench.golden
  plutarch-test/goldens/list.type.uplc.eval.golden
  plutarch-test/goldens/list.type.uplc.golden
  plutarch-test/plutarch-base/Plutarch/ListSpec.hs
  plutarch-test/plutarch-extra/Plutarch/HelloSpec.hs
  plutarch-test/plutarch-extra/Plutarch/ListUtilsSpec.hs
  plutarch-test/plutarch-test.cabal
Labels: testing, plutarch-extra

#386 FFI documentation in the guide
  docs/README.md
  docs/Usage/FFI.md
  plutarch-test/conditional/Plutarch/FFISpec.hs
Labels: documentation

#398 Nix'ify docs website, and check for broken links in CI
  .gitattributes
  docs/DEVGUIDE.md
  docs/Introduction/Plutarch Types.md
  docs/Troubleshooting.md
  docs/Typeclasses/PConstant and PLift.md
  docs/Typeclasses/PIsDataRepr and PDataFields.md
  docs/examples/BASIC.md
  docs/examples/VALIDATOR.md
  docs/index.md
  docs/index.yaml
  flake.lock
  flake.nix
Labels: documentation

#395 Cleanup `Plutarch.Test.Property` (and export?)
  plutarch-test/common/Plutarch/Test/Property.hs
  plutarch-test/common/Plutarch/Test/Property/Extra.hs
  plutarch-test/common/Plutarch/Test/Property/Gen.hs
  plutarch-test/common/Plutarch/Test/Property/HaskEquiv.hs
  plutarch-test/common/Plutarch/Test/Property/Marshal.hs
  plutarch-test/common/Plutarch/Test/Property/Util.hs
  plutarch-test/plutarch-base/Plutarch/ListSpec.hs
  plutarch-test/plutarch-extra/Plutarch/ListUtilsSpec.hs
  plutarch-test/plutarch-test.cabal
Labels: testing
